package com.safari.khourdineshan.viewmodel;

public enum MapUIState {
    FOLLOW_USER_LOCATION,
    DO_NOT_FOLLOW_USER_LOCATION,
    WAITING_FOR_ROUTE_RESPONSE,
    SHOW_ROUTE_BETWEEN_USER_LOCATION_AND_DROPPED_PIN,
    NAVIGATION
}
